=== folio-org/mod-search/src/main/resources/swagger.api/schemas/resourceEvent.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Resource event body",
  "properties": {
    "id": {
      "description": "Resource id",
      "type": "string"
    },
    "type": {
      "description": "Resource event operation type",
      "$ref": "resourceEventType.json"
    },
    "deleteEventSubType": {
      "description": "Resource event delete operation type",
      "$ref": "resourceDeleteEventSubType.json"
    },
    "tenant": {
      "description": "Tenant id",
      "type": "string"
    },
    "resourceName": {
      "description": "Name of resource",
      "type": "string"
    },
    "new": {
      "description": "Instance record new fields",
      "type": "object"
    },
    "old": {
      "description": "Instance record old fields",
      "type": "object"
    }
  }
}

=== folio-org/mod-search/src/test/resources/event/event.json
{
  "id": "55294032-fcf6-45cc-b6da-4420a61ef72c",
  "type": "CREATE",
  "tenant": "diku",
  "resourceName": "authority",
  "new": {
    "id": "55294032-fcf6-45cc-b6da-4420a61ef72c",
    "personalName": "Gary A. Wills",
    "sftPersonalName": [ "a sft personal name" ],
    "saftPersonalName": [ "a saft personal name" ],
    "personalNameTitle": "a personal title",
    "sftPersonalNameTitle": [ "a sft personal title" ],
    "saftPersonalNameTitle": [ "a saft personal title" ],
    "corporateName": "a corporate name",
    "sftCorporateName": [ "a sft corporate name" ],
    "saftCorporateName": [ "a saft corporate name" ],
    "corporateNameTitle": "a corporate title",
    "sftCorporateNameTitle": [ "a sft corporate title" ],
    "saftCorporateNameTitle": [ "a saft corporate title" ],
    "meetingName": "a conference name",
    "sftMeetingName": [ "a sft conference name" ],
    "saftMeetingName": [ "a saft conference name" ],
    "meetingNameTitle": "a conference title",
    "sftMeetingNameTitle": [ "a sft conference title" ],
    "saftMeetingNameTitle": [ "a saft conference title" ],
    "geographicName": "a geographic name",
    "sftGeographicName": [ "a sft geographic name" ],
    "saftGeographicName": [ "a saft geographic name" ],
    "uniformTitle": "an uniform title",
    "sftUniformTitle": [ "a sft uniform title" ],
    "saftUniformTitle": [ "a saft uniform title" ],
    "topicalTerm": "a topical term",
    "sftTopicalTerm": [ "a sft topical term" ],
    "saftTopicalTerm": [ "a saft topical term" ],
    "genreTerm": "a genre term",
    "sftGenreTerm": [ "a sft genre term" ],
    "saftGenreTerm": [ "a saft genre term" ],
    "subjectHeadings": "a subject heading",
    "identifiers": [
      {
        "identifierTypeId": "caaf835f-2037-46c5-9c62-71abaaaa78c5",
        "value": "authority-identifier"
      },
      {
        "identifierTypeId": "d6f3c637-3969-4dc6-9146-6371063f049e",
        "value": "3114176276"
      },
      {
        "identifierTypeId": "c858e4f2-2b6b-4385-842b-60732ee14abb",
        "value": "3745-1086"
      }
    ],
    "metadata": {
      "createdDate": "2021-11-14T12:00:00.000+00:00",
      "createdByUserId": "09934b6d-2940-4c48-b96b-d2f5b439e50e",
      "updatedDate": "2021-11-15T15:00:00.000+00:00",
      "updatedByUserId": "f0f94ee3-eace-4670-84c9-99dee171d2c8"
    },
    "notes": [
      {
        "noteTypeId": "36a62267-d921-4904-bfd1-d2a4958fb67c",
        "value": "an authority note"
      }
    ]
  }
}
